### ISSUE TITLE
Unable to setup build environment

### ISSUE THREAD

**Issue by DasWookie** [horvatkm/space_mouse_esp32s2#1]
Been trying to get this setup so I can build the project and possibly contribute to helping solve and get this spun up and working with an ESP32 as well, as I was thinking the exact same thing for the better micro to use.

Can you please document your build environment and how to set it up. Try as I might, I can't seem to piece it together to get it to build.

**Comment by horvatkm** [comment]
It's not Arduino project. Unfortunately, Arduino framework doesn't support changing VID/PID of USB HID device on Espressif devices, similarly to Leonardo/Arduino pro micro boards. That's why I've used Espressif development framework.

There is nothing special in project setup.
1. download and install latest ESP-IDF
2. launch ESP-IDF 5.2 CMD, change directory to project folder
3. idf.py set-target esp32s2
4. idf,py build
5.  and finally flash it to the device
   idf.py -p PORT flash
   
I don't think you can make it work with original ESP32, since it can use USB port as UART console only. In order to be able to create HID device, you need either ESP32-S2 or ESP32-S3 . 

For development, it's better to use ESP32-S3-DevKit . Even though developing on ESP32-S2 boards, is possible, it's kind of pain in the azz, because they have single USB port and it can't serve both as HID device and UART console. Therefore you'd need switch the device manually to download mode before each flashing.
